# Generated by Django 5.2.8 on 2026-01-04 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorshipcard',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='mentorship_images/'),
        ),
        migrations.AlterField(
            model_name='mentorshipcard',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='mentorshipcard',
            name='destination_link',
            field=models.URLField(help_text='Where this card links to (e.g. WhatsApp, Telegram)'),
        ),
        migrations.AlterField(
            model_name='mentorshipcard',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
